#+TITLE: TAOCP 简介

* 来自官方网站的信息

The Art of Computer Programming (TAOCP)

** 第1卷

Fundamental Algorithms, Third Edition (Reading, Massachusetts: Addison-Wesley, 1997), xx+650pp. ISBN 0-201-89683-4

Volume 1 Fascicle 1, MMIX: A RISC Computer for the New Millennium (2005), v+134pp. ISBN 0-201-85392-2

*** 早先版本的翻译

管纪文和苏运霖，计算机程序设计技巧，第1卷：基本算法（北京：国防工业出版社，1980），14+573页

*** 第三版翻译

苏运霖，计算机程序设计艺术，第1卷：基本算法（北京：国防工业出版社，2002），xx+625页

*** 分册翻译

参见[[第1卷分册翻译]]

** 第2卷

Seminumerical Algorithms, Third Edition (Reading, Massachusetts: Addison-Wesley, 1997), xiv+762pp. ISBN 0-201-89684-2

*** 早先版本的翻译

管纪文和苏运霖，计算机程序设计技巧，第2卷：半数值算法（北京：国防工业出版社，1992），10+622页

*** 第三版翻译

苏运霖，计算机程序设计艺术，第2卷：半数值算法（北京：国防工业出版社，2002），xii+760页

** 第3卷

Sorting and Searching, Second Edition (Reading, Massachusetts: Addison-Wesley, 1998), xiv+780pp.+foldout. ISBN 0-201-89685-0

*** 第一版翻译

管纪文和苏运霖，计算机程序设计技巧，第3卷：排序和查找（北京：国防工业出版社，1985），viii+645页

*** 第二版翻译

苏运霖，计算机程序设计艺术，第3卷：排序和查找（北京：国防工业出版社，2002），x+779页

** 第4A卷

Combinatorial Algorithms, Part 1 (Upper Saddle River, New Jersey: Addison-Wesley, 2011), xvi+883pp. ISBN 0-201-03804-8

香港的培生教育亚洲分社正在准备中文版出版事宜

第四卷的初稿曾作为平装的分册出版，在第4A卷的硬皮版完成之前，有如下分册发行流通

Volume 4 Fascicle 0, Introduction to Combinatorial Algorithms and Boolean Functions (2008), xii+216pp. ISBN 0-321-53496-4

Volume 4 Fascicle 1, Bitwise Tricks & Techniques; Binary Decision Diagrams (2009), xiii+261pp. ISBN 0-321-58050-8

Volume 4 Fascicle 2, Generating All Tuples and Permutations (2005), v+128pp. ISBN 0-201-85393-0

Volume 4 Fascicle 3, Generating All Combinations and Partitions (2005), vi+150pp. ISBN 0-201-85394-9

Volume 4 Fascicle 4, Generating All Trees; History of Combinatorial Generation (2006), vi+120pp. ISBN 0-321-33570-8

这些分册的翻译如下

Volume 4 Fascicle 0, under the direction of Lin Peng Huang (Beijing: Chinese Machine Press, 2010), xii+432pp.

更多分册翻译，参见[[第4A卷分册翻译]]

** 第4B卷

第4B卷现有一个分册已出版，其将作为该卷的中间三分之一的内容，如下

Volume 4 Fascicle 6, Satisfiability (2015), xiii+310pp. ISBN 978-0-13-439760-3

另有一些“准分册”作为alpha测试之用，可以直接从Knuth的网页下载到，它们是

Pre-Fascicle 5a (Mathematical Preliminaries Redux)

Pre-Fascicle 5b (Introduction to Backtracking)

** 第5卷

Syntactic Algorithms

正在准备中，预计将会在2025年完成。

** 未来的计划

在持续写作第4卷和第5卷的同时，Knuth也在整理新近出现的本属于第1--3卷的内容，这些内容也会以分册的形式陆续发布。

第5卷完成后，Knuth会再次更新第1--3卷，特别是，上述分册的内容会在那时组入1--3卷中。

然后，Knuth会发布1--5卷的"读者摘要"版本，把最重要的材料压缩到一本合集之中。

如果一切顺利，在1--5卷完成之后，Knuth计划发布第6卷和第7卷

** 勘误和增补

Knuth的勘误包括error（错误），amendments（修订），plans（计划），improvements（改进）四种类型，其严重程度依次降低。

如下的链接中，标注“全”的为上述四种类型都包含的勘误版本，未标明的仅包含前三种类型的勘误。

*** 第1卷

**** 勘误

[[file:errata/1/err1-2e.ps.gz][第2版勘误]]

[[file:errata/1/all1-pre.ps.gz][第3版勘误（全）]]


[[file:errata/1/err1.ps.gz][2010年之后的勘误]]

[[file:errata/1/all1.ps.gz][2010年之后的勘误（全）]]


[[file:errata/1/err1f1.ps.gz][第1分册勘误]]

[[file:errata/1/all1f1.ps.gz][第1分册勘误（全）]]

**** 增补

[[file:errata/1/1-appc.ps.gz][附录C]]

*** 第2卷

**** 勘误

[[file:errata/1/err2-2e.ps.gz][第2版勘误]]

[[file:errata/1/all2-pre.ps.gz][第3版勘误（全）]]


[[file:errata/1/err2.ps.gz][2010年之后的勘误]]

[[file:errata/1/all2.ps.gz][2010年之后的勘误（全）]]

**** 增补

[[file:errata/1/2-appc.ps.gz][附录C]]

*** 第3卷

**** 勘误

[[file:errata/1/err3-1e.ps.gz][第1版勘误]]

[[file:errata/1/all3-pre.ps.gz][第2版勘误（全）]]


[[file:errata/1/err3.ps.gz][2010年之后的勘误]]

[[file:errata/1/all3.ps.gz][2010年之后的勘误（全）]]

**** 增补

[[file:errata/1/3-appc.ps.gz][附录C]]

*** 第4A卷

**** 勘误

[[file:errata/1/err4f0.ps.gz][第0分册勘误]]

[[file:errata/1/all4f0.ps.gz][第0分册勘误（全）]]

[[file:errata/1/err4f1.ps.gz][第1分册勘误]]

[[file:errata/1/all4f1.ps.gz][第1分册勘误（全）]]

[[file:errata/1/err4f2.ps.gz][第2分册勘误]]

[[file:errata/1/all4f2.ps.gz][第2分册勘误（全）]]

[[file:errata/1/err4f3.ps.gz][第3分册勘误]]

[[file:errata/1/all4f3.ps.gz][第3分册勘误（全）]]

[[file:errata/1/err4f4.ps.gz][第4分册勘误]]

[[file:errata/1/all4f4.ps.gz][第4分册勘误（全）]]


[[file:errata/1/err4a.ps.gz][第1版勘误]]

[[file:errata/1/all4a.ps.gz][第1版勘误（全）]]


[[file:errata/1/err4f6.ps.gz][第6分册勘误]]

[[file:errata/1/all4f6.ps.gz][第6分册勘误（全）]]

* 来自互联网的资料

** 第1卷分册翻译

苏运霖，计算机程序设计艺术 第1卷第1册（双语版） MMIX:新千年的RISC计算机（北京：机械工业出版社，2006），268页 ISBN 7-111-18031-3

** 第4A卷分册翻译

黄林鹏 等，计算机程序设计艺术 第4卷第0册（双语版） 组合算法与布尔函数概论（北京：机械工业出版社，2010），432页 ISBN 7-111-30334-3

苏运霖，计算机程序设计艺术 第4卷第2册（双语版） 生成所有元组和排列（北京：机械工业出版社，2006），267页 ISBN 7-111-17773-8

苏运霖，计算机程序设计艺术 第4卷第3册（双语版） 生成所有组合和分划（北京：机械工业出版社，2006），317页 ISBN 7-111-17774-6

苏运霖，计算机程序设计艺术 第4卷第4册（双语版） 生成所有树 组合生成的历史（北京：机械工业出版社，2007），230页 ISBN 7-111-20825-9

** 关于所有分册的资料

互联网网址
http://www.cs.utsa.edu/~wagner/knuth/
中有关于目前释出的所有分册的下载链接。

其中没有处理到的分册是第8a分册。

当然，也许还有其他一些分册释出，但我也还没找到...

